-- Generated by the database client.
CREATE TABLE users (
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);

CREATE INDEX idx_users_name_search ON public.users USING gin (name gin_trgm_ops);

CREATE INDEX idx_users_created_at ON public.users USING btree (created_at);